### ISSUE TITLE
导入项目安装之后，点击app立马奔溃

### ISSUE THREAD

**Issue by lmdiloveu** [androidmalin/RengwuxianRxjava#7]
05-13 15:55:51.362 28153-28153/com.malin.rengwuxianrxjava E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.malin.rengwuxianrxjava, PID: 28153
                                                                            java.lang.VerifyError: com/malin/rengwuxianrxjava/activity/MainActivity$AjcClosure1
                                                                                at com.malin.rengwuxianrxjava.activity.MainActivity.rxJavaSolveMiZhiSuoJinAndNestedLoopAndCallbackHell(MainActivity.java:334)
                                                                                at com.malin.rengwuxianrxjava.activity.MainActivity.onCreate(MainActivity.java:133)
                                                                                at android.app.Activity.performCreate(Activity.java:5241)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2247)
                                                                                at android.app.ActivityThread.access$800(ActivityThread.java:139)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:136)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5028)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
                                                                                at dalvik.system.NativeStart.main(Native Method)

**Comment by androidmalin** [comment]
已经修复了.
